col DEFAULT_TABLESPACE format a20
col PROFILE format a20
col LAST_LOGIN format a40
select USERNAME,ACCOUNT_STATUS,LOCK_DATE,EXPIRY_DATE,CREATED,DEFAULT_TABLESPACE,PROFILE,LAST_LOGIN from dba_users order by 1,2;